In [1]:
using LinearAlgebra, Ferrite, ModularEIT


SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up


In [2]:
n = 63 
grid = generate_grid(Quadrilateral, (n, n));
∂Ω = union(getfacetset.((grid,), ["left", "top", "right", "bottom"])...)
fe  = FerriteFESpace{RefQuadrilateral}(grid,2,3,∂Ω)

FerriteFESpace{RefQuadrilateral}(CellValues{Ferrite.FunctionValues{1, Lagrange{RefQuadrilateral, 2}, Matrix{Float64}, Matrix{Vec{2, Float64}}, Matrix{Vec{2, Float64}}, Nothing, Nothing}, Ferrite.GeometryMapping{1, Lagrange{RefQuadrilateral, 1}, Matrix{Float64}, Matrix{Vec{2, Float64}}, Nothing}, QuadratureRule{RefQuadrilateral, Vector{Float64}, Vector{Vec{2, Float64}}}, Vector{Float64}}(Ferrite.FunctionValues{1, Lagrange{RefQuadrilateral, 2}, Matrix{Float64}, Matrix{Vec{2, Float64}}, Matrix{Vec{2, Float64}}, Nothing, Nothing}(Lagrange{RefQuadrilateral, 2}(), [0.47237900077244527 -1.4605338811812958e-17 … 1.8551212633834227e-18 0.007620999227554982; -0.05999999999999999 1.4605338811812958e-17 … -1.8551212633834227e-18 -0.059999999999999984; … ; 0.2749193338482966 -8.50014503228635e-18 … -8.500145032286352e-18 -0.03491933384829665; 0.15999999999999984 0.3999999999999998 … 0.3999999999999999 0.15999999999999992], [0.47237900077244527 -1.4605338811812958e-17 … 1.8551212633834227e-18 0.0076

In [3]:
assemble_boundary_matrices(fe)

(sparse([1, 2, 3, 4, 5, 1, 2, 3, 4, 5  …  374, 500, 502, 503, 504, 374, 500, 502, 503, 504], [1, 1, 1, 1, 1, 2, 2, 2, 2, 2  …  503, 503, 503, 503, 503, 504, 504, 504, 504, 504], [0.00846560846560844, -0.0010582010582010544, -0.0010582010582010544, 0.0021164021164021074, 0.00211640211640211, -0.0010582010582010544, 0.00846560846560847, 0.0, 0.00211640211640211, 0.0  …  0.0021164021164021226, 0.0, 0.002116402116402125, 0.016931216931216988, 0.0, 0.0, 0.002116402116402125, 0.0021164021164021226, 0.0, 0.016931216931216988], 504, 504), sparse([1, 2, 3, 4, 5, 1, 2, 3, 4, 5  …  374, 500, 502, 503, 504, 374, 500, 502, 503, 504], [1, 1, 1, 1, 1, 2, 2, 2, 2, 2  …  503, 503, 503, 503, 503, 504, 504, 504, 504, 504], [222.60000000000088, 13.650000000000087, 13.650000000000059, -115.50000000000055, -115.50000000000041, 13.650000000000087, 226.8000000000007, -6.300000000000027, -81.90000000000032, 18.900000000000098  …  -81.89999999999979, 18.899999999999945, -115.49999999999991, 386.39999999999895, 

In [4]:
fe.BDO.MΓ

504×504 SparseArrays.SparseMatrixCSC{Float64, Int64} with 2048 stored entries:
⎡⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠂⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⣀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⎦

In [ ]:
function assemble_boundary_M_K(facetvalues::FacetValues, dh::DofHandler, ∂Ω,b_dofs)
    ndof = ndofs(dh)
    M = allocate_matrix(fe.dh)
    K = allocate_matrix(fe.dh)
    n_basefuncs = getnbasefunctions(facetvalues)
    Me = zeros(n_basefuncs, n_basefuncs)
    Ke = zeros(n_basefuncs, n_basefuncs)

    for facet in FacetIterator(dh, ∂Ω)
        fill!(Me, 0.0); fill!(Ke, 0.0)
        reinit!(facetvalues, facet)
        dofs = celldofs(facet)
        for q in 1:getnquadpoints(facetvalues)
            dΓ = getdetJdV(facetvalues, q)
            for i in 1:n_basefuncs
                φᵢ  = shape_value(facetvalues, q, i)
                ∇φᵢ = shape_gradient(facetvalues, q, i)  # tangential grad on the facet manifold
                for j in 1:n_basefuncs
                    φⱼ  = shape_value(facetvalues, q, j)
                    ∇φⱼ = shape_gradient(facetvalues, q, j)
                    Me[i, j] += φᵢ * φⱼ * dΓ
                    Ke[i, j] += (∇φᵢ ⋅ ∇φⱼ) * dΓ
                end
            end
        end
        for (a, A) in enumerate(dofs), (b, B) in enumerate(dofs)
            M[A, B] += Me[a, b]
            K[A, B] += Ke[a, b]
        end
    end
    return M[b_dofs, b_dofs], K[b_dofs, b_dofs]
end

function assemble_boundary_M_K(fe::FerriteFESpace)
    assemble_boundary_M_K(fe.facetvalues, fe.dh, fe.∂Ω, fe.b_dofs)
end

assemble_boundary_M_K (generic function with 2 methods)

In [24]:
b_dofs = fe.b_dofs
function get_i_dofs(b_dofs, n::Integer)
    is_boundary = falses(n)
    is_boundary[b_dofs] .= true
    return findall(!, is_boundary)
end
i_dofs = get_i_dofs(b_dofs, fe.n)

15625-element Vector{Int64}:
     3
     6
     7
     9
    11
    13
    14
    15
    17
    19
     ⋮
 16111
 16113
 16115
 16117
 16119
 16121
 16123
 16125
 16129

In [27]:
K = fe.K
Kii = K[i_dofs, i_dofs]
kbb = K[b_dofs, b_dofs]
Kib = K[i_dofs, b_dofs]
Kbi = K[b_dofs, i_dofs]

504×15625 SparseArrays.SparseMatrixCSC{Float64, Int64} with 3976 stored entries:
⎡⠿⠤⠤⠄⠤⠤⠠⢤⡄⣄⣀⣀⣀⢀⣀⡀⣀⣀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠁⠉⠉⠉⠉⠈⠉⠁⠉⠉⠘⠛⠂⠒⠒⠒⠒⠐⠲⣶⎦

In [ ]:
M_Γ, K_Γ = assemble_boundary_M_K(fe::FerriteFESpace)

(sparse([1, 2, 3, 4, 5, 1, 2, 3, 4, 5  …  374, 500, 502, 503, 504, 374, 500, 502, 503, 504], [1, 1, 1, 1, 1, 2, 2, 2, 2, 2  …  503, 503, 503, 503, 503, 504, 504, 504, 504, 504], [0.00846560846560844, -0.0010582010582010544, -0.0010582010582010544, 0.0021164021164021074, 0.00211640211640211, -0.0010582010582010544, 0.00846560846560847, 0.0, 0.00211640211640211, 0.0  …  0.0021164021164021226, 0.0, 0.002116402116402125, 0.016931216931216988, 0.0, 0.0, 0.002116402116402125, 0.0021164021164021226, 0.0, 0.016931216931216988], 504, 504), sparse([1, 2, 3, 4, 5, 1, 2, 3, 4, 5  …  374, 500, 502, 503, 504, 374, 500, 502, 503, 504], [1, 1, 1, 1, 1, 2, 2, 2, 2, 2  …  503, 503, 503, 503, 503, 504, 504, 504, 504, 504], [222.60000000000088, 13.650000000000087, 13.650000000000059, -115.50000000000055, -115.50000000000041, 13.650000000000087, 226.8000000000007, -6.300000000000027, -81.90000000000032, 18.900000000000098  …  -81.89999999999979, 18.899999999999945, -115.49999999999991, 386.39999999999895, 

In [16]:
M_test = M_Γ |> Symmetric

504×504 Symmetric{Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}:
  0.00846561  -0.0010582   -0.0010582   …    ⋅           ⋅          ⋅ 
 -0.0010582    0.00846561   0.0              ⋅           ⋅          ⋅ 
 -0.0010582    0.0          0.00846561       ⋅           ⋅          ⋅ 
  0.0021164    0.0021164    0.0              ⋅           ⋅          ⋅ 
  0.0021164    0.0          0.0021164        ⋅           ⋅          ⋅ 
   ⋅          -0.0010582     ⋅          …    ⋅           ⋅          ⋅ 
   ⋅           0.0021164     ⋅               ⋅           ⋅          ⋅ 
   ⋅            ⋅            ⋅               ⋅           ⋅          ⋅ 
   ⋅            ⋅            ⋅               ⋅           ⋅          ⋅ 
   ⋅            ⋅            ⋅               ⋅           ⋅          ⋅ 
  ⋮                                     ⋱                          
   ⋅            ⋅            ⋅          …    ⋅           ⋅          ⋅ 
   ⋅            ⋅            ⋅               ⋅           ⋅          ⋅ 
   ⋅  

In [14]:
Mb, Kb = M_Γ |> Matrix |> Symmetric , K_Γ |> Matrix |> Symmetric

([0.00846560846560844 -0.0010582010582010544 … 0.0 0.0; -0.0010582010582010544 0.00846560846560847 … 0.0 0.0; … ; 0.0 0.0 … 0.016931216931216988 0.0; 0.0 0.0 … 0.0 0.016931216931216988], [222.60000000000088 13.650000000000087 … 0.0 0.0; 13.650000000000087 226.8000000000007 … 0.0 0.0; … ; 0.0 0.0 … 386.39999999999895 -50.399999999999835; 0.0 0.0 … -50.399999999999835 386.3999999999987])

In [46]:
λM, _ = eigen(Mb)
λK, _ = eigen(Kb)
println("$(minimum(λM))")
println("$(maximum(λK))")

0.004864418796367361
482.9055878442602


In [15]:
λ, Φ = eigen(Kb, Mb) 

GeneralizedEigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
504-element Vector{Float64}:
  6801.077429376347
  6801.07742937642
  6801.077429376424
  6801.077429376465
  8932.728242800937
  8932.77466228132
  8932.774662281327
  8932.822397431755
  8940.16308492843
  8940.348501419117
     ⋮
 68274.47566312845
 68408.58575097671
 68413.29658653359
 68413.2965865336
 68417.44596970722
 72948.32856778351
 72948.32856778847
 72948.32856778853
 72948.32856779352
vectors:
504×504 Matrix{Float64}:
 -1.85355e-21  -5.43676e-8   …  -0.0483281     5.12686    3.79395
  1.51179e-21  -1.34739e-8      -0.0360568     3.82507    2.83061
 -3.03367e-21  -1.34739e-8      -0.0360568     3.82507    2.83061
  5.51719e-23  -3.66984e-8       0.0232248    -2.46379   -1.82324
  1.67095e-21  -3.66984e-8       0.0232248    -2.46379   -1.82324
  4.31876e-21  -3.13023e-9   …  -0.0227817     2.41678    1.78845
 -1.54528e-21  -6.46866e-9       0.0141001    -1.4958    -1.10692
  5.56377e-21  -7.27204e

In [19]:
minimum(λ)

6801.077429376347

In [17]:
A(s) = Mb * Φ * Diagonal((1.0 .+ λ).^s) * Φ' * Mb |> Symmetric

A (generic function with 1 method)

In [31]:
Hn½ = A(-0.5)
H½ = A(0.5)

504×504 Symmetric{Float64, Matrix{Float64}}:
  1.23384      -0.083902     -0.083902     …   1.01521e-16  -3.12357e-17
 -0.083902      1.31144      -0.0161238        2.04811e-16   5.7445e-17
 -0.083902     -0.0161238     1.31144         -5.99434e-17  -5.22528e-18
 -0.226306     -0.0743961     0.0659812       -1.46942e-16  -1.7489e-16
 -0.226306      0.0659812    -0.0743961       -1.00026e-16   4.45685e-17
 -0.00441946   -0.113864      9.93867e-5   …  -1.22824e-16   2.27524e-17
  0.0180074    -0.0488927    -0.000451889     -9.7495e-18   -3.98248e-17
 -0.000425545  -0.00313222    6.81773e-6      -3.14859e-16  -5.82072e-17
  0.001516      0.0125316    -2.9927e-5        1.77308e-16  -1.46966e-17
 -4.63779e-5   -0.000304288   4.52647e-7      -4.67394e-18   1.38629e-17
  ⋮                                        ⋱                
  2.70824e-16  -1.67845e-16   1.30932e-17  …  -4.36093e-5    0.00123327
 -2.41448e-18   1.26459e-17  -1.87496e-16      1.40343e-5   -0.000440389
 -1.36747e-16  -8.823

In [33]:
H½inv = inv(H½)

504×504 Symmetric{Float64, Matrix{Float64}}:
  0.85253       0.0563258     0.0563258    …  -2.4002e-17    1.12866e-17
  0.0563258     0.775222      0.0110892       -6.00948e-17  -2.18556e-17
  0.0563258     0.0110892     0.775222         1.40624e-17  -3.22047e-18
  0.0933856     0.0282729    -0.0126211        1.76681e-17   3.02375e-17
  0.0933856    -0.0126211     0.0282729        1.74194e-17  -2.05958e-18
  0.00678058    0.0687831     0.00124206   …   3.44366e-17  -8.36972e-18
 -0.00277978    0.019058     -0.000472309     -3.79089e-18   6.48833e-18
  0.000929295   0.00763964    0.00016382       9.54691e-17   2.24259e-17
 -0.000609174  -0.00214063   -0.000105494     -3.44247e-17   1.66723e-18
  0.000137017   0.000999494   2.37195e-5       1.16227e-18  -3.9258e-18
  ⋮                                        ⋱                
 -1.44794e-16   9.82389e-17   2.97079e-19  …  -0.000150079  -0.000539043
  7.78271e-19   3.32914e-18   6.81255e-17      1.50445e-5    0.000122885
  6.92046e-17   5.0

In [37]:
maximum(Mb * H½inv * H½inv - Hn½)

0.006623785622304377